name: tm_school
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.5

  cupertino_icons: ^1.0.2
  keyboard_dismisser: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.6
  animated_notch_bottom_bar: ^1.0.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  bloc: ^8.1.4
  dio: ^5.4.3+1
  get_it: ^7.7.0
  youtube_player_flutter: ^9.0.1
  image_picker: ^1.1.2
  open_file: ^3.3.2
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  bounce: ^1.0.2
  motion: ^2.0.0
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.3
  device_preview: ^1.1.0
  path_provider: ^2.1.3
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dashboard/
    - assets/home/
    - assets/icons/
    - assets/icons/signin/
    - assets/icons/profile/
    - assets/images/
    - assets/courses/
    - assets/saved/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Thin.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend-Black.ttf
